branch-defaults:
  master:
    environment: GitteacherBackend-env
environment-defaults:
  GitteacherBackend-env-1:
    branch: master
    repository: gitteacher-repo
global:
  application_name: Gitteacher-Backend
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js running
    on 64bit Amazon Linux/4.5.3
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
